config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :albums do
    resources :songs
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :name, presence: true
  validates_length_of :name, maximum: 100
  before_save(:titleize_album)

  private
    def titleize_album
      self.name = self.name.titleize
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.all
    render :index
  end

  def new
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:notice] = "Album successfully added!"
      redirect_to albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album= Album.find(params[:id])
    if @album.update(album_params)
      flash[:alert] = "Album successfully updated"
      redirect_to albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash[:notice] = "Album successfully deleted"
    redirect_to albums_path
  end

  private
    def album_params
      params.require(:album).permit(:name, :genre)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

    render :index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def new
    @album = Album.find(params[:album_id])
    @song = @album.songs.new
    render :new
  end

  def create
    @album = Album.find(params[:album_id])
    @song = @album.songs.new(song_params)
    if @song.save
      redirect_to album_path(@album)
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:album_id])
    @song = Song.find(params[:id])
    render :edit
  end

  def update
    @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to album_path(@song.album)
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to album_path(@song.album)
  end

  private
    def song_params
      params.require(:song).permit(:name, :lyrics)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/edit.html.erb
<h1>Edit album</h1>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit  %>
<% end %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<% if @albums.any? %>
  <ul>
    <% @albums.each do |album| %>
      <li><%= link_to album.name, album_path(album) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no albums yet.</p>
<% end %>


<p><%= link_to "Create new album", new_album_path %></p>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "layouts/album_form" %>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit  %>
<% end %>

<% binding.pry %>

<% if @album.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @album.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<h3><%= @album.genre %></h3>

<% if @album.songs.any? %>
  <h4>Here are the songs for this album:</h4>

  <% @album.songs.each do |song| %>
    <ul>
      <li>
        <%= link_to song.name, album_song_path(@album, song) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No songs are listed for this album.</p>
<% end %>

<p><%= link_to "Add a song", new_album_song_path(@album) %></p>

<p><%= link_to "Edit", edit_album_path(@album) %></p>
<p><%= link_to "Delete album", album_path(@album),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to albums", albums_path %></p>

app/views/home/index.html.erb
<h1>Home</h1>


<p><%= link_to "Go to albums", albums_path %></p>

app/views/layouts/_album_form.html.erb
<%= render "layouts/errors", :object => @album %>

<%= form_for @album do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <%= f.submit %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRecordStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% content_for(:navbar) do %>
  <li><a href="/">Home</a></li>
  <li><a href="something/else">Something else</a></li>
  <li><a href="etc">Etc.</a></li>
<% end %>

  <%= flash[:alert] %>
  <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Edit song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/new.html.erb
<h1>Add a new song:</h1>

<%= form_for [@album, @song] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :lyrics %>
  <%= f.text_area :lyrics %>
  <p><%= f.submit %></p>
<% end %>

app/views/songs/show.html.erb
<h1>Song: <%= @song.name %></h1>
<h2>Album: <%= @album.name %></h2>
<h3><%= @song.lyrics %></h3>

<p><%= link_to "Edit song", edit_album_song_path(@album, @song) %></p>
<p><%= link_to "Delete song", album_song_path(@album, @song),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to album", album_path(@album) %></p>